name: AutoBuild

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - uses: xu-cheng/latex-action@v3
        with:
          root_file: DictionaryOfNewspeak.tex
          texlive_version: 2022
          latexmk_use_xelatex: true
          extra_fonts: |
            ./fonts/*.ttf
            ./fonts/*.TTF
            ./fonts/*.ttc
            ./fonts/*.TTC
            ./fonts/*.otf
            ./fonts/*.OTF
      
      - uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: DictionaryOfNewspeak.pdf